### PR TITLE
Iterm2 Support

### PR DESCRIPTION
**Pull request by JarrettAzar**
Hi!
I love the colorscheme and use it on my linux machine daily, you can see examples of how i set up my computer to match it in my [dotfiles](https://github.com/JarrettAzar/dotfiles)! I also use a mac, so i ported it to iterm2.

Hopefully this is helpful!
Thanks for the cool colorscheme

### CODE REVIEW

**Comment by JarrettAzar** [comment]
If you need I can write a small readme with images on how to install to iterm2. Let me know!

**Comment by sainnhe** [comment]
Wow, many thanks for porting it to iterm2 :)
Yeah, it might be better to add a readme. As for screenshot, it is best not to put the image file in the screenshot folder, because it will enlarge the size of this repo. You can add a screenshot by this way:
1. Drag image file to the input box of any github comment area.
2. After getting the url, use markdown syntax to make it effective.
In fact, the screenshot of zsh-pure-power is added by this way.

**Comment by JarrettAzar** [comment]
Okay! The README is in there now, let me know if you'd like any changes!

**Comment by sainnhe** [comment]
Thank you very much :)

**Comment by sainnhe** [comment]
Sorry for bothering, could you update color scheme of iterm2? A lot of things have been changed since [commit f57de72](https://github.com/sainnhe/vim-color-forest-night/commit/f57de7223d65441e63a5fd4e50bd07ab84811180), and the palette of terminal colors have been changed too(for example [kitty](https://github.com/sainnhe/vim-color-forest-night/blob/master/kitty/forest-night.conf))

**Comment by JarrettAzar** [comment]
Absolutely! Will work on it soon and get it to you tonight :)

**Comment by sainnhe** [comment]
Many thanks!

**Pull request merged**
