### PR TITLE
Added airline theme

### PR DESCRIPTION
**Pull request by termlimit**
Added https://github.com/vim-airline/vim-airline theme

### CODE REVIEW

**Comment by sainnhe** [comment]
Thank you very much!
Could you add a short description about how to use airline theme in README.md?

**Comment by termlimit** [comment]
Done! Glad to help

**Comment by sainnhe** [comment]
Thank you again for airline support :)

**Comment by sainnhe** [comment]
I've adjusted the design of airline theme to match lightline theme, because the original design used some color outside the color scheme and I think it didn't match the hue of this color scheme.

Otherwise all seem to be working. Thank you again for the airline theme!

**Comment by termlimit** [comment]
O cool, thanks for the update. Glad to help!

**Pull request merged**
